config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'

  get 'about/index'

  get 'services/index'

  get 'home/index'

  devise_for :users

  root to: "home#index"
  resources :home
  resources :reserve
  resources :services
  resources :about
  resources :contact
  
end

app/models/driver.rb
class Driver < ActiveRecord::Base
	has_one :vehicle
	has_many :reservations, dependent: :destroy
	has_many :users, through: :reservations
	validates :dname, presence: true
	validates :contact, presence: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :reservation
	validates fare: presence: true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_one :payment
	belongs_to :driver
	belongs_to :user
	validates :to, presence: true
	validates :from, presence: true
	validates :status, presence: true
	validates :Reservation_type, presence: true
	# geocoded_by :to, :from
	# after_validation :geocode #:if => to_changed?
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :drivers, through: :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :uname, presence: true
  validates :contact, presence: true, length: { is: 11 }
  validates :encrypted_password, presence: true, length: { minimum: 8 }
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	belongs_to :driver
	validates :model, presence: true
	validates :reg_num, presence: true
	validates :color, presence: true

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController
	def new
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Taxi Press</title>
    <meta name="description" content="HTML framework description">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Styles -->
    <link rel="stylesheet" href="css/general.css">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Rufina' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>

    <!-- Modernizr -->
    <script type='text/javascript' src='js/libs/modernizr-2.8.3.min.js'></script>

    <!-- Semantic HTML5 Support on old IE -->
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body class="about all">

	<!-- Orange & Black -->
	<div class="background">
		<div class="col-6"></div>
		<div class="col-6"></div>
	</div>

    <div id="call-us" class="call-us">
        <div class="selected">
            <span>Berlin</span>

            <ul>
                <li data-num="#790">Berlin</li>
                <li data-num="#780">London</li>
                <li data-num="#740">Chisinau</li>
            </ul>
        </div>
        <div class="number">#790</div>
        <p>Call us any time</p>
    </div>

	<!-- Nav -->
	<nav class="main">
        <a class="logo" href="index.html"></a>

        <div class="col-6 left">
            <ul class="first cf">

                <li><%=link_to "Reservation", new_reserve_path%></li>
                <li class="dot">•</li>
                <li>
                    <%=link_to "Services", services_path%>
                    <ul class="second">
                        <li><%=link_to "Personal", services_path%></li>
                        <li><%=link_to "Family", services_path%></li>
                        
                        <li><%=link_to "Ladies", services_path%></li>
                    </ul>
                </li>
                <li class="dot">•</li>
                <li><%=link_to "Home", "/home/index"%></li>
            </ul>
        </div>
        <div class="col-6 right">
            <ul class="first cf">
                <li class="dot show-tablet">•</li>
                
                <li class="active"><%=link_to "About", "/about/index"%></li>
                <li class="dot">•</li>
                <li><%=link_to "Contact", "/contact/index"%></li>
                <li class="dot">•</li>
                <li class="active"><a href="">Log In</a></li>
            </ul>
        </div>

        <!-- -->
        <a href="#" class="mobile-button">Menu</a>
        <ul class="mobile-menu">
            <li><a href="index.html">Home</a></li>
            <li>
                <a>Services</a>
                <ul class="second">
                    <li><a href="services.html">Services</a></li>
                    <li><a href="services.html">VIP taxi</a></li>
                    <li><a href="services.html">Regular</a></li>
                        
                </ul>
            </li>
            <li><a href="booking.html">Booking</a></li>
            <li>
                <a>Blog</a>
                <ul class="second">
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="blog.html">News</a></li>
                    <li><a href="blog.html">Sport</a></li>
                    <li><a href="blog-inside.html">Single</a></li>
                </ul>
            </li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>

		<!-- Search -->
		<div class="search-button"></div>
		<form class="search" action="#">
			<input type="text" placeholder="Search"/>
			<input type="submit" value=" "/>
		</form>

	</nav>


    <!-- Content -->
    <div class="wrap">
        <section class="content">

            <h2>About Us</h2>
            <div class="breadcrumb">
                <a href="index.html">Homepage</a>
                <div class="line"></div>
                <a href="about.html">About</a>
            </div>

            <h3>There are many variations of passages of Lorem Ipsum available</h3>

            <div class="cf info">
                <div class="col-6">
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                        alteration in some form, by injected humour, or randomised words which don't look even slightly
                        believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet
                        tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
                        It uses a dictionary of over 200 Latin
                    </p>
                </div>
                <div class="col-6">
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                        alteration in some form, by injected humour, or randomised words which don't look even slightly
                        believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet
                        tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.
                    </p>
                </div>
            </div>

        </section>
    </div>

    <!-- Team -->
    <div class="team">
        <div class="background"></div>
        <div class="wrap">

            <h3>Meet our team</h3>

            <div class="founder">
                <div class="name">
                    Michael<br/>
                    Thompson
                </div>
                <div class="img">
                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                </div>
                <div class="info">
                    <span>Founder / CEO</span>
                    <div class="cf social">
                        <a href="" class="twitter"></a>
                        <a href="" class="facebook"></a>
                        <a href="" class="message"></a>
                    </div>
                </div>

                <div class="wide-line">
                    <img src="css/images/team-wide-line.png" alt=""/>
                </div>

                <div class="team-slider">
                    <ul class="slides">
                        <li class="cf">
                            <div class="col-3">
                               <div class="img">
                                   <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                               </div>
                               <h4>Nicholas Stephens</h4>
                               <span>VIP taxi driver</span>
                            </div>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                    <h4>Tomothy Rogers</h4>
                                    <span>Taxi driver</span>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                    <h4>Bob Harper</h4>
                                    <span>Taxi driver</span>
                                    <div class="social">
                                        <a href="" class="message"></a>
                                        <a href="" class="facebook"></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                    <h4>Rosemary May</h4>
                                    <span>Accounter</span>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                </div>
                                <h4>Nicholas Stephens</h4>
                                <span>VIP taxi driver</span>
                            </div>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                    <h4>Tomothy Rogers</h4>
                                    <span>Taxi driver</span>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                    <h4>Bob Harper</h4>
                                    <span>Taxi driver</span>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="img">
                                    <img src="http://placehold.it/127x127/fcf8eb/" alt=""/>
                                    <h4>Rosemary May</h4>
                                    <span>Accounter</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <!-- Certificate -->
    <div class="certificate">
        <div class="wrap cf">
            <div class="col-7">
                <div class="text">
                    <h3>
                        There are many
                       <span>variations of passages</span>
                    </h3>
                    <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority
                        have suffered alteration in some form, by injected humour
                    </p>
                </div>
            </div>
            <div class="col-5">
                <img src="http://placehold.it/321x419/fcf8eb/" alt=""/>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer id="footer">
		<div class="content">
			<div class="wrap cf">
				<div class="col-4">
					<p>
						There are many variations of passages of Lorem Ipsum available generated Lorem Ipsum is therefore
						always free from repetition, injected humour, or non-characteristic...
					</p>
					<p>
						© 2014 Taxi Press. All rights reserved
					</p>
				</div>
				<div class="col-4">
                    <div class="call">
						<h3>#790</h3>
	                    <span>Call us any time</span>
                    </div>
				</div>
				<div class="col-4">
					<p>Our adress:</p>
					<span>UK, Manchester, 8417 Parker Rd</span>

                    <div class="social">
                        <a href="https://twitter.com/alethemes" target="_blank" class="twitter"></a>
                        <a href="https://www.facebook.com/alethemes" target="_blank" class="facebook"></a>
                        <a href="https://www.youtube.com/user/CRIK0VA" target="_blank" class="youtube"></a>
                    </div>
				</div>
			</div>
		</div>

	    <!-- -->
	    <div class="bottom-line">
		    <div class="wrap">
                <a href="blog.html">Our blog</a>
                <div class="dot"></div>
                <a href="contact.html">Contact form</a>
                <div class="dot"></div>
                <a href="about.html">About us</a>
		    </div>
	    </div>
    </footer>

    <!-- Libs -->
    <script src="js/libs/jquery-1.11.3.min.js"></script>
    <script src="js/libs/jquery.flexslider-min.js"></script>

    <!-- Custom -->
    <script src="js/scripts.js"></script>

    <script>
        initAbout();
    </script>

</body>
</html>

app/views/contact/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Taxi Press</title>
    <meta name="description" content="HTML framework description">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Styles -->
    <link rel="stylesheet" href="css/general.css">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Rufina' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>

    <!-- Modernizr -->
    <script type='text/javascript' src='js/libs/modernizr-2.8.3.min.js'></script>

    <!-- Semantic HTML5 Support on old IE -->
    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body class="contact all">

	<!-- Orange & Black -->
	<div class="background">
		<div class="col-6"></div>
		<div class="col-6"></div>
	</div>

    <div id="call-us" class="call-us">
        <div class="selected">
            <span>Berlin</span>

            <ul>
                <li data-num="#790">Berlin</li>
                <li data-num="#780">London</li>
                <li data-num="#740">Chisinau</li>
            </ul>
        </div>
        <div class="number">#790</div>
        <p>Call us any time</p>
    </div>

	<!-- Nav -->
	<nav class="main">
        <a class="logo" href="index.html"></a>

        <div class="col-6 left">
            <ul class="first cf">

                <li><%=link_to "Reservation", new_reserve_path%></li>
                <li class="dot">•</li>
                <li>
                    <%=link_to "Services", services_path%>
                    <ul class="second">
                        <li><%=link_to "Personal", services_path%></li>
                        <li><%=link_to "Family", services_path%></li>
                        <li><%=link_to "Ladies", services_path%></li>
                    </ul>
                </li>
                <li class="dot">•</li>
                <li><%=link_to "Home", "/home/index"%></li>
            </ul>
        </div>
        <div class="col-6 right">
            <ul class="first cf">
                <li class="dot show-tablet">•</li>
                <li><%=link_to "About", "/about/index"%></li>
                <li class="dot">•</li>
                <li class="active"><%=link_to "Contact", "/contact/index"%></li>
                <li class="dot">•</li>
                <li class="active"><a href="">Log In</a></li>
            </ul>
        </div>

        <!-- -->
        <a href="#" class="mobile-button">Menu</a>
        <ul class="mobile-menu">
            <li><a href="index.html">Home</a></li>
            <li>
                <a>Services</a>
                <ul class="second">
                    <li><a href="services.html">Services</a></li>
                    <li><a href="services.html">VIP taxi</a></li>
                    <li>
                        <a href="services.html">Regular</a>
                        <ul class="third">
                            <li><a href="services.html">Reto Cab</a></li>
                            <li><a href="services.html">VIP axi</a></li>
                            <li><a href="services.html">Regular</a></li>
                            <li><a href="services.html">Airport meeting</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a href="booking.html">Booking</a></li>
            <li>
                <a>Blog</a>
                <ul class="second">
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="blog.html">News</a></li>
                    <li><a href="blog.html">Sport</a></li>
                    <li><a href="blog-inside.html">Single</a></li>
                </ul>
            </li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>

		<!-- Search -->
		<div class="search-button"></div>
		<form class="search" action="#">
			<input type="text" placeholder="Search"/>
			<input type="submit" value=" "/>
		</form>

	</nav>


    <!-- Content -->
    <div class="inner">

        <!-- Back -->
        <div class="back-left"></div>
        <div class="back-right"></div>

        <!-- Content -->
        <div class="wrap cf">
            <div class="col-6 left">
                <h2>Taxi <span>Press</span></h2>
                <p>
                    There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                    alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
                </p>

                <div class="line"></div>

                <span>Our adress:</span>
                <p>UK, Manchester, 8417 Parker Rd</p>
                <br/>
                <span>Phone for clients:</span>
                <p class="phone">800 436-67-90, 800 436-67-10</p>
                <br/>
                <div class="line"></div>

                <div class="social">
                    <a href="#" class="twitter"></a>
                    <a href="#" class="facebook"></a>
                    <a href="#" class="youtube"></a>
                </div>

            </div>
            <div class="col-6 right">
                <h3>Contact with us</h3>

                <div class="form">
                    <form action="#">
                        <label for="name">Name:</label>
                        <input type="text" id="name"/>
                        <label for="email">Email:</label>
                        <input type="text" id="email"/>
                        <label for="message">Message:</label>
                        <textarea name="message" id="message"></textarea>
                        <input type="submit" value="Send"/>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <!-- Map -->
    <section class="map">
        <!--<img src="css/images/map.jpg" alt=""/>-->
        <iframe class="grayscale" src="https://maps.google.com/maps?q=google+maps+london&amp;ie=UTF8&amp;hq=&amp;hnear=%D0%9B%D0%BE%D0%BD%D0%B4%D0%BE%D0%BD,+%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B1%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D0%B8%D1%8F&amp;gl=md&amp;ll=51.511214,-0.119824&amp;spn=0.191731,0.528374&amp;t=m&amp;z=12&amp;output=embed"></iframe>
    </section>

    <!-- Footer -->
    <footer id="footer">
		<div class="content">
			<div class="wrap cf">
				<div class="col-4">
					<p>
						There are many variations of passages of Lorem Ipsum available generated Lorem Ipsum is therefore
						always free from repetition, injected humour, or non-characteristic...
					</p>
					<p>
						© 2014 Taxi Press. All rights reserved
					</p>
				</div>
				<div class="col-4">
                    <div class="call">
						<h3>#790</h3>
	                    <span>Call us any time</span>
                    </div>
				</div>
				<div class="col-4">
					<p>Our adress:</p>
					<span>UK, Manchester, 8417 Parker Rd</span>

					<div class="social">
						<a href="https://twitter.com/alethemes" target="_blank" class="twitter"></a>
						<a href="https://www.facebook.com/alethemes" target="_blank" class="facebook"></a>
						<a href="https://www.youtube.com/user/CRIK0VA" target="_blank" class="youtube"></a>
					</div>
				</div>
			</div>
		</div>

	    <!-- -->
	    <div class="bottom-line">
		    <div class="wrap">
			    <a href="blog.html">Our blog</a>
			    <div class="dot"></div>
			    <a href="contact.html">Contact form</a>
			    <div class="dot"></div>
			    <a href="about.html">About us</a>
		    </div>
	    </div>
    </footer>

    <!-- Libs -->
    <script src="js/libs/jquery-1.11.3.min.js"></script>
    <script src="js/libs/jquery.flexslider-min.js"></script>

    <!-- Custom -->
    <script src="js/scripts.js"></script>

    <script>

    </script>

</body>
</html>